### ISSUE TITLE
items get lost

### ISSUE THREAD

**Issue by josefwho** [peregrinustyss/Till#112]
items fly through borders etc. gamebreaking.

**Comment by mcloister** [comment]
tried to catch items that are flying around when they are checked for being in the basket at customer.cs. if an item is at extreme position it will now be stopped and ignored for basket check (which means a customer will leave even if that crazy flying item is not in basket).
I also zoomed out a tiny bit and added extra barriers at conveyor outside of the camera. hope this helps prevent the bug even if it doesn;t fix it :)
