### ISSUE TITLE
Stats Ticker at bottom of Title Screen

### ISSUE THREAD

**Issue by mcloister** [peregrinustyss/Till#130]
Inludes: Fired Count, Below Minimum Wage Count, Above Minimum Wage Count, Totoal Shifts Player, Maximum Wage earned, Max Items Per Shift, Max Bonus Reached, Total Items Scanned Count,

**Comment by josefwho** [comment]
inlcude current goal to unlock something

**Comment by josefwho** [comment]
think of more stats to include...
