### ISSUE TITLE
change number in stamp

### ISSUE THREAD

**Issue by josefwho** [peregrinustyss/Till#145]
should be relative to that what the stamp is saying

**Comment by mcloister** [comment]
what stamp? the wage stamp? can you give an example than I can probably easily change it!

**Comment by josefwho** [comment]
at the end you made 950€ and thats above minimum wage. 
But first there is the number and then the minimum wage stamp. I think a lot of people will therefore think that they made 950€ above minimum wage. And that is quite a lot and the contrary we want them to think. 
So it would be better if the number in the stamp is relative to the minimum wage. So for example if he made 950 than the number would say you just made 250€ above minimum wage (I don't have in mind what the actual minimum wage was). But do you know what I mean?

I think it gets better readable then.
