### ISSUE TITLE
Write texts for AMAZE submission

### ISSUE THREAD

**Issue by mcloister** [peregrinustyss/Till#84]

**Comment by josefwho** [comment]
Pitch first try:

CHESTO At the Checkout is a game commentary about modern day society with attention to social fabric (=gesellschaftliches Gefüge), consumption and the gap between rich and poor.
You are playing a supermarket cassier who tries to do work as hard as he can to achieve just about his minimum legal wage and at the same time he is contributing to the growth of a global food retail chain and his owner's astronomical wealth.
